---

- name: Check if Manager node is Leader
  shell: docker node ls | grep {{ ansible_hostname }}
  register: docker_info
  changed_when: false

- name: Fail if Manager node is not Leader
  assert:
    that:
      - "'Leader' in docker_info.stdout"
      - "'Drain' in docker_info.stdout"
